Add missing feature to regex dep
Without this, I get the following error:

```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  regex parse error:
      https?://[^\s)]+
                 ^^
  error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```